### ISSUE TITLE
Consider renaming develop to master

### ISSUE THREAD

**Issue by bast** [dev-cafe/libgetkw#2]
And master to something else since develop seems to contain latest code and personally I find it more intuitive for developers if bleeding edge is on master.

**Comment by robertodr** [comment]
Yep, agreed!

**Comment by bast** [comment]
I can do the rename but how should we call current master?

**Comment by stigrj** [comment]
The mrchem2 branch can safely be deleted, it's not used anymore

**Comment by robertodr** [comment]
The `pcmsolver` branch is also good to go. @ilfreddy is the `luca` branch still in use anywhere or can we delete it?

**Comment by bast** [comment]
Is the code using any versioning? If not, I would also simply delete master and rename develop to master. How does that sound? (And I will remove the other branches that you have flagged to be removed).

**Comment by robertodr** [comment]
:+1: As long as the juselius/libgetkw repo stays alive, we can get all of these back in some way.

**Comment by bast** [comment]
Or to be on the safe side I tag current master with an annotated tag and explain what it is so that in a post-apocalyptic world humanity will be able to figure out what happened.

**Comment by bast** [comment]
OK I will now do the branch switcheroo. I will notify you once it's done.

**Comment by bast** [comment]
- tagged old master
- removed old master
- renamed develop to master
- protected master
- removed pcmsolver and mrchem2

Closing.
