### ISSUE TITLE
PYTHON_VERSION not set

### ISSUE THREAD

**Issue by stigrj** [dev-cafe/libgetkw#30]
It seems the CMake variables `PYTHON_VERSION_MAJOR`, `PYTHON_VERSION_MINOR` etc. are not set when building `getkw` independently, so the Python modules are installed under `python./site-packages/`.

What's the correct way to set these variables? In MRChem they are set in `cmake/downloaded/autocmake_python_interpreter.cmake`. Should I add the same here?

**Comment by bast** [comment]
You can take inspirations from here:
- https://github.com/dev-cafe/cmake-cookbook/blob/master/chapter-03/recipe-01/example/CMakeLists.txt
- https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html
